### ISSUE TITLE
Add notes about DNS views

### ISSUE THREAD

**Issue by spacekpe** [isc-projects/isc-dnssec-guide#2]
I think that marka has very very important note about internal/external DNS views which are often used in companies:
http://www.ietf.org/mail-archive/web/dnsop/current/msg11833.html

This could be nicely acompanied with general advice not to use views at all:
https://lists.isc.org/mailman/private/bind-workers/2014-October/003280.html

**Comment by samorris** [comment]
Hi Petre

Thanks for the issue and apologies that it's taken so long to address it.

The updates to the guide being made in the 2020-updates branch include, in the "Commonly Asked Questions" section, advice to use the same dnssec-policy (and hence keys) for all instances of a zone appearing in different views.  The branch will be merged later this year.  However, I think that advice not to use views at all falls outside the scope of this guide.
